### ISSUE TITLE
Unable to install on windows because of no top level folder in zip archive from release.

### ISSUE THREAD

**Issue by AmadMuhammad** [YahiaAngelo/MaterialMapGenerator#1]
On windows the addon zip archive from the release download section would not install because because the __init.py__ and other files are put directly put into the archive . But blender expects to have a folder in the zip and the files inside it . IF you clone the repo you get it in the form which blender expects.

**Comment by YahiaAngelo** [comment]
Yup, I just noticed that, and it's fixed in the latest release.
Thanks!
